### ISSUE TITLE
header flicker

### ISSUE THREAD

**Issue by 03hchen** [GTBitsOfGood/jennifer-anns-group#113]
Header flickers on refresh (and sometimes when you first visit the page) from unauthorized view to authorized view

**Comment by nathangong** [comment]
@03hchen I think the split second flicked is inevitable since that's how long it takes for the auth state to be loaded in. Would you prefer there to be a loading indicator there or just make it empty until its loaded?

**Comment by 03hchen** [comment]
hmm I'll ask LT
