### ISSUE TITLE
Themes & Tags Schema & Endpoints

### ISSUE THREAD

**Issue by 03hchen** [GTBitsOfGood/jennifer-anns-group#22]
## Description

An admin should be able to create new themes and tags and connect them to various games.

Create the Theme Schema that follows the requirements below:
* name: String, unique, required
~~* games: array reference to game Object IDs, optional~~

Create the Tag Schema that follows the requirements below:
* name: String, unique, required
* enum: ["Accessibility", "Custom"]
~~* games: array reference to game Object IDs, optional~~

Modify the Game Schema and any necessary endpoints to follow the requirements below:
* OLD: theme: String, optional --> NEW: themes: **array** reference to theme Object IDs, optional (nonprofit is now allowing multiple themes
* OLD: tags: String[], optional --> NEW: tags: array reference to tag Object IDs, optional

UPDATE: Games will hold references to several themes/tags, but themes/tags will NOT hold references to games.

~~Themes/tags and games will have a [many-to-many relationship](https://www.mongodb.com/community/forums/t/many-to-many-relationship-and-linked-table-collection/130305), meaning that games will hold references to several themes/tags and themes/tags will hold references to several games.~~

Additionally, create API endpoints (with associated actions) for the following:
* `POST api/themes` - creates a new theme
* `POST api/tags` - creates a new tag
* `DELETE api/themes/[id]` - deletes the theme with the specified id. this should also delete all references to the theme from the `themes` array in the associated games (but not the games themselves)
* `DELETE api/tags/[id]` - deletes the tag with the specified id. this should also delete all references to the tag from the `tags` array in the associated games (but not the games themselves)
~~* modify `DELETE api/games/[id]` - deletes the game. this endpoint already exists, but make sure this action also deletes all references to the game in the associated themes and tags~~
* modify `POST api/games` - adds a game. this endpoint already exists, but add the associated themes and tag ids instead of their names ~~but make sure that the themes and tags collections are also updated based on the themes and tags array for the new game.~~
* modify `PUT api/games/[id]` - modify a game. this endpoint already exists, but add the associated themes and tag ids instead of their names ~~but make sure that the themes and tags collections are also updated based on the themes and tags array for the new game.~~

## Acceptance Criteria

- [x] Create Theme and Tag Schemas that follows the requirements listed above
- [x] Modify Game schema and any necessary endpoints to follow the requirements listed above
- [x] Create new endpoints
- [x] Proper error handling for the new endpoints
- [x] Update backend to account for new changes (including accessibility tags)

So sorry for the changes to your ticket!! Feel free to submit it by Sunday or next Tuesday and let me know if you need more time!

## Other Notes
* See `src/pages/api`, `src/server/db/models`, `src/server/db/actions`, and `src/utils/types/index.ts` for how existing backend code is structured
* Filtering games by themes and tags will be implemented in a later ticket.
* Most of the work in this ticket should be pretty repetitive, but there are a lot of requirements, so don't be afraid to let me know if this is too much and we can modify the ticket!
* Don't be afraid to reach out for help!

**Comment by Duckierstone42** [comment]
Hey Helen!

I should be able complete the additional request by Sunday night.

And no worries, these things happen!
