### ISSUE TITLE
Research Embedding Games

### ISSUE THREAD

**Issue by 03hchen** [GTBitsOfGood/jennifer-anns-group#7]
## Description

The nonprofit would like us to embed their existing games that currently exist across several platforms into our one application. We need to research how to embed games into our application. 

Why: Most of their games are on [itch.io](https://itch.io/), and one solution the nonprofit approves is to just put links on our platform that redirect to itch.io. The problem with this redirecting method is that some schools block itch.io (due to mature content), so students at these schools would not be able to play these games. Links are also boring, and they don't look very professional. Overall, the nonprofit prefers to not rely on third party servers like itch.io. 

Additional Context: The nonprofit has the ability to host all the games on their own servers. Most games have been developed in Unity and have a web template, but some are downloadable. If the game is downloadable, it is fine for there just to be an option to download through our application. Some games also use Flash, but since Flash is no longer available these games have to be converted to WebGL. These games may be out of scope for our application.

Here are some games they currently have:
* [https://jag.itch.io/](https://jag.itch.io/)
* [consent.games](http://consent.games/)
* [playhoneymoon.com](http://playhoneymoon.com/)
* [rispekdanis.com](http://rispekdanis.com/)

They currently do not have a compiled list of all the games they own but hopefully will be able to gather one for us soon. 

We'd like for the nonprofit to be able to add games to the CMS themselves, so it'd be nice if there could be a way for them to upload games somehow.

## Acceptance Criteria

- [x] Look into how game files can be uploaded into our CMS by the nonprofit (through an Add A Game option or similar)
- [x] Look into how these files can be stored into our database (MongoDB)
- [x] Look into how we can embed web browser games into our application for users to view
- [x] Your findings can be in the form of a comment, Google Doc, and/or test code on the `/dummy` page

## Other Notes
* This ticket is more vague than the others, so let me know if you need any other clarifications for this ticket!

**Comment by 03hchen** [comment]
UPDATE: Most games that will be added to our application will be web browser games. These games will be uploaded in an archive zip or rar format which will include an index.html page and any other necessary pages for the game. The nonprofit will send us a sample archive so that we can use it for testing purposes on our end. I'll add a comment to this page when that happens!

Some games may be downloadable Window or Linux games that also come with an archive file as well as instructions for how to download, extract, and start the game. We will also get a sample file for these types of games but we don't have to worry about these right now since most games that will be added to our application will be web browser games.

**Comment by 03hchen** [comment]
From the nonprofit!

Below is a link to a folder with three archives for MushWhom:
a Windows build
a Linux build
a WebGL build
All are zip archives and should be able to be opened with all major operating systems.
https://drive.google.com/drive/folders/1osLDIpkt-Fk0Esf4Sl8Y0xgoUcWrEOHz

I think you can focus on the WebGL build. That should work for most Mac and Windows software. There may be an issue with Linux, but that's not really my area of expertise. Drew will probably be able to confirm 100% at our Friday meeting.

Let me know if you have any more questions about the ticket!

**Comment by nathangong** [comment]
I've found a system for uploading and running WebGL builds! Running a WebGL build in a React/Next frontend is very simple. There's a library called `react-unity-webgl` that provides a `Unity` component, which can be instantiated in a component like so:
```js
const { unityProvider } = useUnityContext({
  loaderUrl: "game_file.loader.js",
  dataUrl: "game_file.data",
  frameworkUrl: "game_file.framework.js",
  codeUrl: "game_file.wasm",
});

return (
  <>
    <Unity unityProvider={unityProvider} />
  </>
);
```
Since we want to store games on the cloud, the urls should link to a backend endpoint that returns the respective file. 

On the backend side, since WebGL builds can be quite large (and the BSON-document size limit is only 16 megabytes), it seems that MongoDB's GridFS service is the best option. I was able to get a simple express backend API with file upload and download to work with it. Here's parts of the most relevant code:
```js
const client = new MongoClient(mongoURI);
let gfs;

client.connect().then(() => {
  const db = client.db(dbName);
  gfs = new GridFSBucket(db, { bucketName: "webglBuilds" });

  app.listen(port, () => {
    console.log(`Server running on port ${port}`);
  });
});

app.use(
  fileUpload({
    useTempFiles: true,
    tempFileDir: "/tmp/",
  })
);

// file upload endpoint
app.post("/webglbuild", (req, res) => {
  const file = req.files.file;
  const readStream = fs.createReadStream(file.tempFilePath);
  readStream.pipe(gfs.openUploadStream(file.name));
  readStream.on("end", () => {
    res.send("success");
  });
  readStream.on("erorr", () => {
    res.send("error");
  });
});

// file download endpoint
app.get("/webglbuild/:filename", (req, res) => {
  gfs
    .find({ filename: req.params.filename })
    .toArray()
    .then((files) => {
      if (!files || files.length === 0) {
        return res.status(404).json({ err: "no files exist" });
      }
      const readStream = gfs.openDownloadStreamByName(req.params.filename);
      readStream.pipe(res);
    });
});
```
The upload endpoint might be a bit inefficient, since it requires someone to manually upload each of the 4 build files, so in the future we might want to change it to make uploading games more streamlined. I unfortunately couldn't test Windows or Linux builds since I'm on a Mac. Please let me know if anything was unclear or if you have any questions!

**Comment by 03hchen** [comment]
More clarification from the nonprofit:

We create a variety of builds and ideally would have all builds available for all games. However, we generally don't do so due to the time involved or due to limitations unique to that particular game. 

That said, with the exception of WebGL builds, all other builds would just be a hyperlink in the form of an icon or a line of text; the actual build would reside elsewhere and your application would simply be opening a connection to allow that linked content to be downloaded to the requestor's computer / tablet / phone. 

WebGL builds are different in that they are played within a web browser and so there is the possibility to allow them to play the WebGL game "within" your application. I place that in quotes because we have the option of embedding games in a frame within your application but the actual build itself resides elsewhere. For example, it would appear to the visitor that they are playing a game within your application but in reality the game itself is hosted on itchio. Alternatively, the game build is on the same server as the presentation layer of your application and in that instance it could be said to be played within your application. I do not know if this distinction will matter for your purposes.

Here is a list of all possible/likely game builds:

- Amazon App (linked to Amazon Apps storefront)
- Android App (probably only for sideloading so not storefront-specific, instead linked to any repository for downloading)
- Appstore (linked to Apple/iTunes)
- Linux download (linked to any repository for downloading)
- Mac download (linked to any repository for downloading)
- WebGL [this is the only one that might actually be played "within" your application]
- Windows download (linked to any repository for downloading)

Below is a screenshot from a quite outdated website of ours [JAGga.me](https://jagga.me/) to show how we have used icons to indicate the different types of available builds.

![image](https://github.com/GTBitsOfGood/jennifer-anns-group/assets/72580357/eacd671b-1c46-43da-b36e-65b48a2633cb)

Tooltips are used to offer more info in a pop-up box when hovering over the icons.

In addition to the WebGL builds which could exist within the application, we could also do the same with video trailers. It is not necessary to embed the videos as we can simply link to them but, as with WebGL builds, we do have the option of embedding videos from Vimeo (preferable) or YouTube within the application.
