### ISSUE TITLE
Test New Games

### ISSUE THREAD

**Issue by 03hchen** [GTBitsOfGood/jennifer-anns-group#84]
Test the new games NP sent us listed under "Games we have yet to test" found on [this Notion page](https://www.notion.so/gtbitsofgood/Sample-Games-and-Links-3d589cbf3a494dba9004fcf51c462bf1). Create new bug tickets for games that our application doesn't support (you don't have to fix them)

**Comment by 03hchen** [comment]
The new games that Susanne sent in `BoG x JaG 2.zip` all follow the same format at Adrift, which means that our WebGL upload option does not work for all the new games.

Our WebGL upload option supports uploading four files (loader, framework, code, data), but all the new games sent are run by the index.html file. 

Solution: ask NP if we need to add an option to upload a folder that we then run the index.html from.

**Comment by nathangong** [comment]
Honeymoon's loader file is not compatible with the standard React Unity WebGL React component, as it doesn't contain the createUnityInstance() function. Running the game works fine by simply serving `index.html`, however there are some styling quirks that would need to be taken care of.
